version: 2.1

# Define reusable steps
executors:
  python-executor:
    docker:
      - image: circleci/python:3.9  # Use the Python Docker image (choose the version you need)
    working_directory: ~/todoapp

# Define the jobs
jobs:
  test:
    executor: python-executor
    steps:
      - checkout  # Checkout the code from the repository
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt  # Install the dependencies
      - run:
          name: Run migrations
          command: |
            . venv/bin/activate
            python manage.py migrate  # Run Django migrations
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python manage.py test  # Run Django tests

# Define the workflows
workflows:
  version: 2
  test:
    jobs:
      - test  # Run the test job